# Generated by Django 4.2.16 on 2026-04-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_department_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='当前token'),
        ),
    ]
