# Generated by Django 4.2.16 on 2026-04-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_current_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='员工姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('department', models.CharField(max_length=50, verbose_name='部门')),
                ('position', models.CharField(max_length=50, verbose_name='岗位')),
                ('employee_status', models.CharField(max_length=20, verbose_name='员工状态')),
                ('job_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='职级')),
                ('household_registration', models.CharField(blank=True, max_length=100, null=True, verbose_name='户籍地')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生年月日')),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('education', models.CharField(blank=True, max_length=20, null=True, verbose_name='学历')),
                ('entry_date', models.DateField(verbose_name='入司日期')),
                ('work_years', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='工龄')),
                ('contract_start_date', models.DateField(verbose_name='合同签订日期')),
                ('contract_end_date', models.DateField(verbose_name='合同到期日期')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='薪资')),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='基本工资')),
                ('performance_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='绩效工资')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='提成')),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='补助')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '员工关系',
                'verbose_name_plural': '员工关系',
                'db_table': 'employee_relation',
                'ordering': ['-created_at'],
            },
        ),
    ]
