# Generated by Django 4.2.16 on 2026-04-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_employeerelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50, verbose_name='候选人')),
                ('recommendation_date', models.DateField(verbose_name='推荐日期')),
                ('department', models.CharField(max_length=50, verbose_name='应聘部门')),
                ('position', models.CharField(max_length=100, verbose_name='应聘岗位')),
                ('source_channel', models.CharField(max_length=50, verbose_name='来源渠道')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='候选人简历')),
                ('resume_file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='简历文件名')),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
                ('education', models.CharField(max_length=20, verbose_name='学历')),
                ('inviting_hr', models.CharField(max_length=50, verbose_name='邀约HR')),
                ('first_interview_time', models.DateTimeField(blank=True, null=True, verbose_name='一面面试时间')),
                ('first_interviewer', models.CharField(blank=True, max_length=50, null=True, verbose_name='一面面试官')),
                ('second_interview_time', models.DateTimeField(blank=True, null=True, verbose_name='二面面试时间')),
                ('second_interviewer', models.CharField(blank=True, max_length=50, null=True, verbose_name='二面面试官')),
                ('interview_result', models.CharField(max_length=50, verbose_name='面试结果')),
                ('expected_arrival_time', models.DateField(blank=True, null=True, verbose_name='预计到岗时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '招聘进度',
                'verbose_name_plural': '招聘进度',
                'db_table': 'recruitment_progress',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, verbose_name='需求部门')),
                ('requester', models.CharField(max_length=50, verbose_name='需求提出人')),
                ('position', models.CharField(max_length=100, verbose_name='需求岗位')),
                ('application_date', models.DateField(verbose_name='申请日期')),
                ('urgency_level', models.CharField(max_length=20, verbose_name='紧急程度')),
                ('required_count', models.IntegerField(verbose_name='需求人数')),
                ('hired_count', models.IntegerField(default=0, verbose_name='已入职人数')),
                ('remaining_count', models.IntegerField(verbose_name='剩余人数')),
                ('personnel_type', models.CharField(max_length=50, verbose_name='人员类别')),
                ('recruitment_status', models.CharField(max_length=50, verbose_name='招聘状态')),
                ('responsible_hr', models.CharField(max_length=50, verbose_name='负责HR')),
                ('work_location', models.CharField(max_length=100, verbose_name='工作地')),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='建议薪资范围')),
                ('job_requirements', models.TextField(blank=True, null=True, verbose_name='岗位要求')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '招聘需求汇总',
                'verbose_name_plural': '招聘需求汇总',
                'db_table': 'recruitment_requirement',
                'ordering': ['-created_at'],
            },
        ),
    ]
