# Generated by Django 4.2.16 on 2026-04-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_recruitmentprogress_recruitmentrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerelation',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='银行卡号'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='银行卡开户行'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='银行卡开户银行名称'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='籍贯'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='合同签订编号'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人姓名'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='紧急联系人电话'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='family_member_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='家庭成员姓名'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='family_member_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='家庭成员电话'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='graduation_school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='毕业院校'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='home_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='家庭住址'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='婚姻状态'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='position_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='岗位工资'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='regularization_date',
            field=models.DateField(blank=True, null=True, verbose_name='转正时间'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='social_security_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='社保缴纳基数'),
        ),
    ]
