# Generated by Django 4.2.16 on 2026-04-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_employeerelation_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerelation',
            name='social_security_date',
            field=models.DateField(blank=True, null=True, verbose_name='社保缴纳时间'),
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='social_security_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否缴纳社保'),
        ),
    ]
