# Generated by Django 4.2.16 on 2026-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_employeerelation_social_security_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentprogress',
            name='actual_interview_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际面试时间'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='expected_interview_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计面试时间'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='expected_onboard_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计入职日期'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='期待薪资'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='first_interview_actual_interviewer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='初试面试官'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='first_interview_actual_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='初试时间'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='first_interview_fail_reason',
            field=models.TextField(blank=True, null=True, verbose_name='初试未通过原因'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='first_interview_result',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='初试结果'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='is_attended',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否到面'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='is_video_interview',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否视频面试'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='job_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职级'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='offer_reply',
            field=models.TextField(blank=True, null=True, verbose_name='OFFER回复'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='offer_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OFFER状态'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='onboard_department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='入职部门'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='onboard_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='入职岗位'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='probation_period',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='转正期限'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='reserve_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='储备状态'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='salary_confirm_standard',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='谈薪确认标准'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='second_interview_actual_interviewer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='复试面试官'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='second_interview_actual_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='复试时间'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='second_interview_fail_reason',
            field=models.TextField(blank=True, null=True, verbose_name='复试未通过原因'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='second_interview_result',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='复试结果'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='social_security_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='社保备注'),
        ),
    ]
