# Generated by Django 4.2.16 on 2026-04-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_recruitmentprogress_actual_interview_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentprogress',
            name='personality_test',
            field=models.FileField(blank=True, null=True, upload_to='personality_tests/', verbose_name='性格测试表'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='personality_test_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='性格测试表文件名'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='registration_form',
            field=models.FileField(blank=True, null=True, upload_to='registration_forms/', verbose_name='应聘登记表'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='registration_form_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='应聘登记表文件名'),
        ),
    ]
