# Generated by Django 4.2.16 on 2026-04-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_recruitmentprogress_personality_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentprogress',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='recruitmentprogress',
            name='salary_confirm_standard',
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='补助'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='基本工资'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='提成'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='performance_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='绩效工资'),
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='position_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='岗位工资'),
        ),
    ]
