# Generated by Django 4.2.16 on 2026-04-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_recruitmentprogress_expected_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentprogress',
            name='reserve_status',
        ),
        migrations.AddField(
            model_name='recruitmentprogress',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='薪资'),
        ),
    ]
