# Generated by Django 4.2.16 on 2026-04-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_recruitmentprogress_interview_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentprogress',
            name='offer_reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='拒绝原因'),
        ),
        migrations.AlterField(
            model_name='recruitmentprogress',
            name='offer_reply',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OFFER回复'),
        ),
    ]
