# Generated by Django 4.2.16 on 2026-04-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_recruitmentprogress_offer_reject_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentprogress',
            name='recommendation_date',
            field=models.DateField(blank=True, null=True, verbose_name='推荐日期'),
        ),
    ]
