# Generated by Django 4.2.16 on 2026-04-20 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_recruitmentprogress_recommendation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='日志ID')),
                ('action', models.CharField(choices=[('LOGIN', '登录'), ('LOGOUT', '登出'), ('CREATE', '新增'), ('UPDATE', '修改'), ('DELETE', '删除'), ('UPLOAD', '上传'), ('DOWNLOAD', '下载'), ('VIEW', '查看'), ('EXPORT', '导出'), ('IMPORT', '导入'), ('OTHER', '其他')], max_length=20, verbose_name='操作类型')),
                ('module', models.CharField(choices=[('系统', '系统'), ('用户管理', '用户管理'), ('招聘管理', '招聘管理'), ('员工关系', '员工关系'), ('其他', '其他')], max_length=20, verbose_name='操作模块')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='对象类型')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='对象ID')),
                ('object_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='对象名称')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='详细内容')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=10, verbose_name='操作状态')),
                ('message', models.TextField(blank=True, null=True, verbose_name='消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='operation_l_user_id_c9af97_idx'), models.Index(fields=['action', 'created_at'], name='operation_l_action_2f1cff_idx'), models.Index(fields=['module', 'created_at'], name='operation_l_module_72e285_idx')],
            },
        ),
    ]
