# Generated by Django 4.2.16 on 2026-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_code', models.CharField(db_index=True, max_length=100, verbose_name='页面代码')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('owner', models.CharField(max_length=50, verbose_name='负责人')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('status', models.CharField(default='进行中', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(default='中', max_length=10, verbose_name='优先级')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='金额')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='目标日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '业务记录',
                'verbose_name_plural': '业务记录',
                'db_table': 'bus_record',
            },
        ),
    ]
