# Generated by Django 4.2.16 on 2026-04-10 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0002_productinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='businessrecord',
            table='business_record',
        ),
        migrations.AlterModelTable(
            name='productinfo',
            table='product_info',
        ),
    ]
