# Generated by Django 4.2.16 on 2026-04-10 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0003_productworkflow_suppliermerchandiser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWorkflow',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('product_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('workflow_type', models.CharField(default='sample', max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('current_stage', models.IntegerField(default=1)),
                ('total_stages', models.IntegerField(default=9)),
                ('progress', models.IntegerField(default=0)),
                ('application_time', models.DateTimeField(auto_now_add=True)),
                ('demand_time', models.DateField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('hot_sales_data', models.TextField(blank=True, null=True)),
                ('product_link', models.URLField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('required_days', models.IntegerField(blank=True, null=True)),
                ('countdown', models.IntegerField(blank=True, null=True)),
                ('full_color_demand_time', models.DateField(blank=True, null=True)),
                ('development_rhythm', models.CharField(blank=True, max_length=50, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('operation', models.CharField(blank=True, max_length=100, null=True)),
                ('product_selling_points', models.TextField(blank=True, null=True)),
                ('product_improvement_points', models.TextField(blank=True, null=True)),
                ('meeting_suggestions', models.TextField(blank=True, null=True)),
                ('approval_time', models.DateTimeField(blank=True, null=True)),
                ('approval_comments', models.TextField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('sample_order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_order_time', models.DateTimeField(blank=True, null=True)),
                ('salesperson_approval_time', models.DateTimeField(blank=True, null=True)),
                ('salesperson_comments', models.TextField(blank=True, null=True)),
                ('operator_approval_time', models.DateTimeField(blank=True, null=True)),
                ('operator_comments', models.TextField(blank=True, null=True)),
                ('photographer_approval_time', models.DateTimeField(blank=True, null=True)),
                ('photographer_comments', models.TextField(blank=True, null=True)),
                ('clerk_approval_time', models.DateTimeField(blank=True, null=True)),
                ('clerk_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_applicants', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_approvers', to=settings.AUTH_USER_MODEL)),
                ('clerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_clerks', to=settings.AUTH_USER_MODEL)),
                ('merchandiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_merchandisers', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_operators', to=settings.AUTH_USER_MODEL)),
                ('photographer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_photographers', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_salespersons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '产品工作流',
                'verbose_name_plural': '产品工作流',
                'db_table': 'product_workflow',
            },
        ),
        migrations.CreateModel(
            name='SupplierMerchandiser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchandiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '供应商跟单员',
                'verbose_name_plural': '供应商跟单员',
                'db_table': 'supplier_merchandiser',
            },
        ),
    ]
