# Generated by Django 4.2.16 on 2026-04-13 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0004_productworkflow_suppliermerchandiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
