# Generated by Django 4.2.16 on 2026-04-14 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0006_alter_businessrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='productinfo',
            name='prod_produc_style_c_5520b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='productinfo',
            name='prod_produc_product_0fb8b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='productinfo',
            name='prod_produc_product_26eca8_idx',
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='eliminate_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='eliminate_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='eliminator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_eliminators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliermerchandiser',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='suppliermerchandiser',
            name='brand_name',
            field=models.CharField(default='', max_length=200, verbose_name='品牌名称'),
        ),
        migrations.AddField(
            model_name='suppliermerchandiser',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='suppliermerchandiser',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='suppliermerchandiser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='current_stage',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='41eac6dc-f9d8-483b-8219-3a7a90387dc2', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='9487c30b-ebb3-4dce-9212-21f5b09fa8dd', max_length=36, unique=True),
        ),
    ]
