# Generated by Django 4.2.16 on 2026-04-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_businessrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='39c0edfe-dccc-4a2d-a4c6-7441890da8cb', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='2845a08d-87c5-4654-8b3c-8daab5a1fd2b', max_length=36, unique=True),
        ),
    ]
