# Generated by Django 4.2.16 on 2026-04-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_productworkflow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='22c6ef09-b526-46af-be29-488a55db4e81', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='f9bda593-e606-4b8e-81ea-a2362783829f', max_length=36, unique=True),
        ),
    ]
