# Generated by Django 4.2.16 on 2026-04-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_productworkflow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='a6032e9a-a50f-48f4-a89c-5f1b22575b33', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='45d29b38-06bf-4b25-ac78-50aab76ce879', max_length=36, unique=True),
        ),
    ]
