# Generated by Django 4.2.16 on 2026-04-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_productworkflow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='1f7331bb-7275-4b23-bde4-79add008c058', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='d9f8295d-fe56-46d5-8997-3f7421d57a6c', max_length=36, unique=True),
        ),
    ]
