# Generated by Django 4.2.16 on 2026-04-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_productworkflow_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='sample_delivery_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='white_background_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='08863514-c976-403b-9f82-29f4de43501b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='0c80102d-9f44-4c12-b264-8aec41524565', max_length=36, unique=True),
        ),
    ]
