# Generated by Django 4.2.16 on 2026-04-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_productworkflow_sample_delivery_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='order_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='order_stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='88710438-ff57-4ab3-9fb6-d120fc474930', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='25619fc4-052c-479f-914d-05b469a64424', max_length=36, unique=True),
        ),
    ]
