# Generated by Django 4.2.16 on 2026-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_productworkflow_order_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='order_items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='order_warehouse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='e1325d15-19bf-4e48-8a74-8dddf422bd1d', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='f02fd3e3-e560-49ad-a6cd-3ea685998827', max_length=36, unique=True),
        ),
    ]
