# Generated by Django 4.2.16 on 2026-04-14 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0014_productworkflow_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='operator_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_operator_leaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='28cf4dce-efcc-4ad5-8574-1f698cee276b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='3ed0b94e-9c7b-4a67-8044-79f4fb6819ce', max_length=36, unique=True),
        ),
    ]
