# Generated by Django 4.2.16 on 2026-04-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_productworkflow_operator_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='order_created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='requested_ship_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='6e08ac0b-35f2-4400-b2e3-3672e6925ec0', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='c0248f03-1b05-43a6-9b25-0c14a9e4d8d0', max_length=36, unique=True),
        ),
    ]
