# Generated by Django 4.2.16 on 2026-04-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_productworkflow_order_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='brand',
            field=models.CharField(default='white_label', max_length=50),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='merchandiser_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='033a7153-f396-403d-a541-0799d23928e9', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='ae20cc3f-75f9-43da-8ec5-3e56bbdf28df', max_length=36, unique=True),
        ),
    ]
