# Generated by Django 4.2.16 on 2026-04-15 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0017_productworkflow_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='accessory_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='applicable_season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='article_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='ds_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='ds_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='ds_six_images_qualified',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='ds_six_images_uploaded',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='ds_system_approval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='expected_completion_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='futures_spot_season',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='has_try_on_report',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='is_ordered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='need_photo_shoot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='need_white_bg_photo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='order_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='photo_shoot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='photo_shoot_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='price_approval_completed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='price_calculator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_price_calculators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='price_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='price_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_price_leaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='price_submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='price_submitted',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='report_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='sample_order_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='selected_platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='shoe_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='shoe_insole',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='style_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='try_on_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='unordered_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='white_bg_fail_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='white_bg_passed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='95e208a5-4a86-4380-809b-11ea970482f4', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='05e0978b-6cec-49e5-853a-acbb991cf64d', max_length=36, unique=True),
        ),
    ]
