# Generated by Django 4.2.16 on 2026-04-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_productworkflow_accessory_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default='b604afff-93e5-48df-9312-ad0132e05e55', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default='811e2321-c15f-4227-adac-2f0111850563', max_length=36, unique=True),
        ),
    ]
