# Generated by Django 4.2.16 on 2026-04-16 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_productworkflow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='product_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
