# Generated by Django 4.2.16 on 2026-04-16 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0020_alter_productworkflow_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='inbound_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_inbound_operators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='inbound_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='production_stage',
            field=models.IntegerField(default=0),
        ),
    ]
