# Generated by Django 4.2.16 on 2026-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_productworkflow_inbound_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='merchandiser_progress_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='merchandiser_progress_records',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
